version: '3.5'
services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "127.0.0.1:9001:9000"
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9009:9009"
    networks:
      mynet:
        aliases:
          - clickhouse.data.mynet

networks:
  mynet:
    external:
      name: mynet